### PR TITLE
mailchimp subscribe block footer

### PR DESCRIPTION
**Pull request by vgrozdanoski**
Needs styling

### CODE REVIEW

**Review by jdleonard — CHANGES_REQUESTED** [review]
After importing the configuration, I'm getting "This block is broken or missing. You may be missing content or you might need to enable the original module." where the footer block content should be.

image

This problem and some possible solutions are described at https://drupal.stackexchange.com/questions/159124/how-do-i-migrate-block-content-from-a-dev-to-a-production-site

I suggest using one of the modules mentioned in the first two solutions so that this block's "content" can be treated as configuration.

**Comment by vgrozdanoski** [comment]
@jdleonard Are you able to edit the block and insert content? If the content is shown, we can just add it to the site.

**Comment by jdleonard** [comment]
@vgrozdanoski Doesn't look like I can:
image

**Comment by jdleonard** [comment]
Closing as you resolved this another way.

**Pull request closed without merging**
